project:
  type: book
  output-dir: docs
  
book:
  title: "Study on Marine Genetic Resources"
  author: "Paul Oldham, Jasmine Kindness, Emmanuel Davidson, Amelia Westmoreland, Thomas Vanagt and Marcel Jaspars"
  date: "February 20 2025"
  body-footer: |
        <!-- 100% privacy-first analytics -->
        <script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
        <noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>
  chapters:
    - index.qmd
    - introduction.qmd
    - scientific_literature.qmd
    - patent_activity_for_marine_genetic_resources.qmd
    - marine_genetic_resources_on_the_web.qmd
    - references.qmd

website:
  title: "Marine Genetic Resources"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - scientific_literature.qmd
      - patent_activity_for_marine_genetic_resources.qmd
      - marine_genetic_resources_on_the_web.qmd
      - references.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    number-depth: 0