---
title: "Introduction"
editor: source
---

The United Nations General Assembly (UNGA) initiated discussions on an international legally binding instrument for the conservation and sustainable use of marine biodiversity in ABNJ in 2017, leading to the launch of intergovernmental negotiations in 2018. These negotiations culminated in the approval of the Biodiversity Beyond National Jurisdiction (BBNJ) treaty in 2023, which addresses a package of elements, including marine genetic resources (MGR) with a focus on benefit-sharing, area-based management tools, environmental impact assessments, and capacity building and technology transfer. Among these, the issue of MGR in ABNJ has generated significant interest and debate. Despite this, the commercial value of these resources remains uncertain. Between 2006 and 2013, the Ad Hoc Open-ended Informal Working Group on marine biodiversity in areas beyond national jurisdiction repeatedly highlighted the need for more research to assess the economic value of MGR in ABNJ to inform decision-making. However, to date, only one comprehensive study has been conducted — in 2014.

The main objective of this study is to provide evidence-based information and analysis on the actual and potential market value of marine genetic resources (MGR) from areas beyond national jurisdiction (ABNJ). This aims to support the implementation of the legally binding BBNJ agreement for the conservation and sustainable use of marine biodiversity beyond national jurisdiction. Building upon previous investigations, this study focused on three specific objectives: 1) mapping recent and planned marine scientific research activities exploring MGR in ABNJ, 2) analyzing the market value and commercialization of MGR from ABNJ through a scientific and patent landscape analysis, and 3) proposing regulatory options for the sharing of monetary benefits derived from the utilization of MGR in ABNJ.

This lack of extensive assessment on the commercial value and market scale of MGR in ABNJ has led to divergent narratives about its potential. Developing countries advocated for monetary benefit-sharing mechanisms, while developed countries expressed concerns about the costs associated with monitoring and implementing such systems. Understanding the actual and potential market value and commercialization of MGR in ABNJ is therefore crucial to shaping and implementing an efficient and equitable benefit-sharing framework.

This project was conducted by a consortium led by ABS International, with the support of One World Analytics and the University of Aberdeen. The methodology employed builds on the earlier work conducted in 2014, which was carried out by the One World Analytics team.
